### PR TITLE
grpcbox workaround

### PR DESCRIPTION
**Pull request by camelpunch**
Special-case grpcbox's `unpackPhase` to match [the workaround provided in this comment](https://github.com/ydlr/mix2nix/pull/18#issuecomment-1708998005).

I've attempted to [push this work upstream](https://github.com/tsloughter/grpcbox/pull/108) but haven't had time to invest in understanding how grpcbox's code is generated.

If mix2nix isn't the best place for this, I'll totally understand!

In order to generate the fixture mix.lock I started a new project and added the existing dependencies to it, as well as grpcbox. As such the mix.lock includes other dependencies, and a changed SHA256, too.

### CODE REVIEW

**Comment by ydlr** [comment]
Thanks @camelpunch . Looks good. Merging now.

**Comment by camelpunch** [comment]
Any chance of a release to nixpkgs with this change? We still need to duplicate it in our setup.

**Comment by ydlr** [comment]
@camelpunch I submitted the update to nixpkgs: https://github.com/NixOS/nixpkgs/pull/281029

Also added flakes support to make it easier to just track master branch in your projects, if that is your thing :)

**Comment by camelpunch** [comment]
Yeah I was considering sending a PR for flake stuff. Thanks for doing that!

**Pull request closed without merging**
